### ISSUE TITLE
[flagd] in-process evaluation mode, and shared evaluation engine

### ISSUE THREAD

**Issue by toddbaert** [open-feature/js-sdk-contrib#614]
As mentioned in flagd documentation of  **Creating an in-process flagd provider** [^1], the in-process provider comes with unique advantages. This issue focuses on creating a TS/JS implementation. The implementation will be server-side, but shareable components (namely the evaluation engine, see tasks below) should be packaged and released separately, so they can be used in a hypothetical client side implementation, browser UI validation, etc.

**Requirements**

- Fulfill requirements outlined by flagd in-process guideline [^1]
- Minimal external dependencies 
- Updated/New ReadMe & usage guide
- Unit & e2e tests (e2e test already exist [here](https://github.com/open-feature/flagd-testbed/tree/main/gherkin)) 

**Technical requirements**

- Build both remote and in-process providers into a single dependency (To be decided after the POC)
- Reuse existing interfaces and implementations where possible 
- Shareable flagd evaluation engine lib published as independent module

**Tasks**

**_NOTE: each of these should be it's own issue. Please ping @toddbaert if you're interested in taking one of these tasks and I will create an issue on-demand._**

- [x] #615
- [x] evaluation engine package
- [x] #626
    - [x] flag definition validation using [the schema](https://github.com/open-feature/schemas/blob/main/json/flagd-definitions.json)
      - [x] [Shared evaluators](https://flagd.dev/reference/flag-definitions/#shared-evaluators)
      - [x] [injected properties](https://flagd.dev/reference/flag-definitions/#flagd-properties-in-the-evaluation-context)
    - [x] Custom JsonLogic evaluators 
      - [x] [Fractional](https://flagd.dev/reference/specifications/custom-operations/fractional-operation-spec/)
      - [x] [Semver](https://flagd.dev/reference/specifications/custom-operations/semver-operation-spec/)
      - [x] [String Comp](https://flagd.dev/reference/specifications/custom-operations/string-comparison-operation-spec/)
- [x] Serverside provider
  - [x] uses evaluation engine package above
  - [x] connects via gRPC sync to get flag definition

[^1]: https://flagd.dev/reference/specifications/in-process-providers/

**Comment by Kavindu-Dodan** [comment]
`evaluation engine package` is also completed with PR https://github.com/open-feature/js-sdk-contrib/pull/620

I am now actively working on `Basic JSONLogic engine shared library`. This should complete the flagd-core part of the implementation

**Comment by Kavindu-Dodan** [comment]
PR https://github.com/open-feature/js-sdk-contrib/pull/623 completes the evaluation engine part of the flagd-core. 

I will now start work on the serverside provider based on the flagd-core library
